pipeline {
    agent any
     stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/RajaniLekkala/team3'
             }
         }
        stage('Build') {
            steps {
                sh "mvn compile"
            }
        }
        stage('Restore Packages') {
            steps {
              bat "dotnet restore"
            }
        }
        stage('Clean') {
   	steps {
    	    bat 'dotnet clean'
   	}
       }
       stage('Build') {
     	steps {
    	     bat 'dotnet build MarysMajesticMovies.sln'
     	}
       }	
       stage('newman') {
            steps {
                sh 'newman run Restful_Booker.postman_collection.json --environment Restful_Booker.postman_environment.json --reporters junit'
            }
            post {
                always {
                     junit '**/*xml'
                }
            }
        }
       
       
     }
    
 }